### ISSUE TITLE
Error with Artifactory

### ISSUE THREAD

**Issue by kbirger** [joelspadin-garmin/vscode-private-extension-manager#11]
Now that you have added the paging toggle, after disabling that on my settings, I get the following error pop up when using the extension:

Unexpected RIGHT_BRACE("}") in state VALUE

I have sniffed the response that the call makes:
Request: <HOST>/artifactory/api
/npm/npm-local/-/v1/search?text=vscode&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0
.5
```
{"objects":[{"package":{"name":"mypackage-vscode","description":"...","maintainers":[],"version":"0.1.0","date":null,"keywords":[],"author":null}}]}
```

While the error seems to suggest malformed JSON, the above seems to be valid.

**Comment by joelspadin-garmin** [comment]
It looks like this error is coming from [jsonparse](https://github.com/creationix/jsonparse/blob/master/jsonparse.js#L321), which is used by minipass-json-stream, which is used by npm-registry-fetch. I'm not sure what could be causing the error, as passing in that text into jsonparse gives me valid output.

You may need to try [building and debugging the extension](https://github.com/joelspadin-garmin/vscode-private-extension-manager/blob/master/README.md#building-and-debugging) yourself to get some more context for the error. If you break on uncaught exceptions and promise rejects like so...
![image](https://user-images.githubusercontent.com/57683567/78150776-5e0c3580-73fd-11ea-9f1b-58c94c07a8dd.png)
...then the debugger should pause when it hits that error, and hopefully we can see what input it's failing on.

**Comment by kbirger** [comment]
Trying to build right now, but I'm getting a node_gyp error. Not sure what the cause is yet,but will keep digging....

>  npm ci

> fsevents@1.2.12 install C:\Users\kbirger\Documents\git\vscode-private-extension-manager\extension\node_modules\watchpack\node_modules\fsevents
> node-gyp rebuild


C:\Users\kbirger\Documents\git\vscode-private-extension-manager\extension\node_modules\watchpack\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2033, in GenerateOutput
    root_entries = _GatherSolutionFolders(
  File "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1791, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1744, in _DictsToFolders
    for folder, contents in bucket.items():
AttributeError: 'MSVSProject' object has no attribute 'items'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\kbirger\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\lib\configure.js
:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kbirger\\AppData\\Roaming\\nvm\\v12.14.0\\node_modules\\npm\\node_modules\\nodenode
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kbirger\Documents\git\vscode-private-extension-manager\extension\node_modules\watchpack\node_modules\fsevents
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
added 804 packages in 37.63s

**Comment by joelspadin-garmin** [comment]
Try deleting node_modules and using `npm install` instead of `npm ci`. I've seen weird issues like that before where NPM thinks it needs to install fsevents even though that's an optional dependency which I think is only for OSX.

**Comment by kbirger** [comment]
Yeah, I managed to get it working with npm install. The error is mysterious though. It seems to throw the error after the very end of parsing the string. I also noticed that for some reason the fetch http call gets called multiple times. Not really sure what to make of all of it because the JSON is valid.

**Comment by joelspadin-garmin** [comment]
It's possible the search request is happening twice because I was lazy and didn't have the tree view and auto update check share a source of data. I figured the caching the NPM libraries do would prevent that, but it probably only applies to package info and not to the search calls.

Do you know exactly which request it was trying to parse when it failed? If Private Extension Manager makes a call for the info for a specific package, then that seems to indicate that it succeeded in parsing the result of the search call since it needs that to know which packages exist.

I did upgrade npm-registry-fetch to the latest version, and it looks like it switched which JSON parsing library it's using to minipass-json-stream, but the [source for that library](https://github.com/npm/minipass-json-stream) no longer seems to exist? I'm not entirely sure what happened there.

**Comment by kbirger** [comment]
The exception is thrown from jsonparse:
```
proto.parseError = function (token, value) {
  this.tState = STOP;
  this.onError(new Error("Unexpected " + Parser.toknam(token) + (value ? ("(" + JSON.stringify(value) + ")") : "") + " in state " + Parser.toknam(this.state)));
};
```

I can catch it in Registry.ts:
```
await npmsearch(query, {
          ...this.options,
          from,
        });
```

Which tells me that the error does come from that search call, unless I'm wrong.

**Comment by joelspadin-garmin** [comment]
Hmm. Since it's running the `npmsearch()` call twice, is one succeeding and the other failing, or do both fail?

**Comment by kbirger** [comment]
Here are my observations. Upon initial load, I see 3 calls to the search. All three fail. Subsequently, when I press the refresh button at the top of the panel, two calls are made. Only the second one fails here.

The second call for me is:

getChildren => getRootChildren => getRecommendedExtensions => getUniquePackages => getPackages => findMatchingPackages

**Comment by joelspadin-garmin** [comment]
It sounds like this is an issue with the latest version of npm-registry-fetch. We'd need to provide the maintainers of that project with a way to reproduce the issue though. "I found an issue that only happens with my private server you can't access" is probably not too helpful. 

It looks like Artifactory does have a free version, so if you can provide steps for setting up Artifactory and code to query it that works in an older version of npm-registry-fetch but not the current version, then we can report this to [npm-registry-fetch](https://github.com/npm/npm-registry-fetch).

You could try using the Node REPL (just run `node` with no arguments) to find a minimal code example that causes the issue, like:

```js
const search = require('libnpmsearch');
search('*', { registry: 'https://localhost:1234' });
```

I would also be interested to know if the issue still happens with the latest versions of libnpmsearch and npm-registry-fetch but with `verifyCache()` commented out, just to rule out some weird interaction between the cache cleaning code and the newer versions of the libraries.

**Comment by joelspadin-garmin** [comment]
Possibly related? https://github.com/npm/npm-registry-fetch/issues/23

**Comment by kbirger** [comment]
Commenting verifyCache doesn't seem to make a difference. I tried your suggestion in terms of making a minimal reproduction by setting up a wiremock to handle the relevant endpoint and to reply with the exact json I received. Unfortunately, it seems to work perfectly :).

Not sure if that issue is related, because the main characteristic of this seems to be a parsing error from the library. I didn't have a chance to look at it in depth, but it seems like a slightly different error.

There is one other thing that has been bothering me. When I look in fiddler, the result looks like this:

```
HTTP/1.1 200 OK
Server: Artifactory/6.10.3
X-Artifactory-Id: ae576ca938320186:1deb3309:16c8cc9321d:-8000
Content-Type: application/json
Transfer-Encoding: chunked
Date: Fri, 03 Apr 2020 20:50:15 GMT

c7
{"objects":[{"package":{"name":"mypackage-vscode","description":"...","maintainers":[],"version":"0.1.0","date":null,"keywords":[],"author":null}
3
}]}
0


```


I'm not sure what those numbered characters are. I mostly think they are an artifact of how Fiddler renders responses, and indeed when stepping through the parser, I didn't see any tokens that I didn't expect. Also, when I run the request through curl, I see nothing odd about the response, but then again I didn't correct for headers.

**Comment by joelspadin-garmin** [comment]
I'm not familiar with how chunked transfer encoding works, but "3" followed by 3 characters and "0" at the end seems to indicate those are the sizes of the following chunks. Maybe the code that receives the response isn't properly putting the chunks back together and garbage data is getting fed into the JSON parser?

**Comment by kbirger** [comment]
I was thinking something along those lines, but I don't see how that would work if all the tokens seem correct. I was debugging with breakpoints however, so maybe I missed something.

Tomorrow I will try to comment out one of the calls and see if I can spot anything else.

Incidentally, what application do you use for your private registry?

**Comment by joelspadin-garmin** [comment]
I believe we're using Sonatype Nexus. Someone else manages that though, so I don't know a whole lot about how we've set it up.

**Comment by kbirger** [comment]
I've noticed that if I return an empty array from getUniquePackages() instead of doing work that after the initial attempt to load the extensions (there's only one call now) which still fails, the remaining calls to findMatchingPackages() generally succeed - I would say over 80% of the time.

**Comment by ChaosinaCan** [comment]
Another idea that might help track this down: If you run the request in fiddler multiple times, does it always get chunked the same way? If you do 2-3 of the same request back to back quickly does it change? 

I wonder if something about the encoding or chunking is changing and only sometimes cause the problem. For example, if a multi-byte Unicode character got split across two chunks and it wasn't recombined properly, that could confuse the parser.

**Comment by joelspadin-garmin** [comment]
Whoops. Was signed into the wrong account. The above comment is also me.

**Comment by kbirger** [comment]
That was a great thought, unfortunately today I tried what you suggested and it didn't reveal anything interesting.
I had to try 6 requests in order to get one that worked, and all 6 had the same positioning of the chunks. 

Was there any objective gain in updating the version of the library? Could we perhaps revert to the stable version while they investigate the issue as it seems they are doing? (Assuming this is the same issue as you linked above). I do believe in helping folks get their packages stable (as we are doing here), but it seems like a dead end so far :(

**Comment by joelspadin-garmin** [comment]
I remember NPM saying there were some potential security vulnerabilities so I updated everything, but I didn't check whether any of those were related to npm-registry-fetch. I'll try backdating and see if any warnings come back.

**Comment by joelspadin-garmin** [comment]
No vulnerabilities in the old versions. I still need to test that everything still works though.

**Comment by joelspadin-garmin** [comment]
@kbirger 4a590aaf1fca88865d98d99689627bd724bf66c6 reverts to the older versions of NPM libraries. Could you test if that works for you?

**Comment by kbirger** [comment]
@joelspadin-garmin It seems to be working just fine for me from source on that commit. You haven't released this new version to the marketplace, right? (I still see 1.1.0 as latest there).

Thank you!

**Comment by kbirger** [comment]
Thanks for the info. Do you have any idea of when you think you'll have the new build available?

**Comment by joelspadin-garmin** [comment]
I just published it. It should show up as an update in a few minutes.

**Comment by kbirger** [comment]
Awesome, thank you! I just got the update, and it worked right away from the first try!

**Comment by joelspadin-garmin** [comment]
Great! I'll start watching npm-registry-fetch to see if they fix any JSON parsing issues.

**Comment by joelspadin-garmin** [comment]
Also, I forgot to respond to this part:

> Regarding that issue you posted: npm/npm-registry-fetch#23
>
> npm-registry-fetch is only used to get the details about specific packages. The happens when doing the search. In other words, the code discussed in this issue is never triggered during the error scenario.

Searches use libnpmsearch, which uses npm-registry-fetch (https://github.com/npm/libnpmsearch/blob/latest/index.js#L47), so everything does end up going through npm-registry-fetch.

**Comment by ChaosinaCan** [comment]
It looks like https://github.com/npm/make-fetch-happen/commit/7f896bef4bbcab73eccb92b5999204b673cdf485 might fix the issue with invalid JSON.

**Comment by kbirger** [comment]
That's great! Give me a shout if you want me to test another build at some point.

**Comment by joelspadin-garmin** [comment]
@kbirger I had some free time to update things. Here's a new build if you'd like to test it. https://github.com/joelspadin-garmin/vscode-private-extension-manager/releases/tag/v1.3.0-beta.0

**Comment by kbirger** [comment]
Thank you @joelspadin-garmin - It seems to work without a problem! I know it says you have only updated the fetch, but I ran it through the end-to-end lifecycle anyway to make sure I can report anything that comes up. I did as below (for records):

- Uninstalled current version
- Installed the beta version through the menu item by pointing to the vsix file
- Reloaded
- Verified that my private repo extension shows up
- Uninstalled the extension
- Reloaded
- Verified that my extension shows up in search results
- Installed it
- Reloaded
- Verified extension functionality to make sure install was right.

Thanks again!

**Comment by joelspadin-garmin** [comment]
Great! I'll include that in the next version then, (whenever I get time to add something to justify a new version).
