### ISSUE TITLE
Cannot install extension which name with scope

### ISSUE THREAD

**Issue by eightHundreds** [joelspadin-garmin/vscode-private-extension-manager#16]
I have verified that if the name has scope, it will report an error during `vsce package` and installation.

But in my company, if you want to publish the package , the name must with the scope

**Comment by joelspadin-garmin** [comment]
[VS Code extensions cannot have scoped names](https://github.com/Microsoft/vscode-vsce/issues/186).

I could do something like rewriting the package.json before installing the extension so that the name is valid, but testing your extension would be difficult, as you'd need to rename it yourself to test it, then rename it back to a scoped name to publish. I can't think of any way to do this that would work very well, though I'm open to suggestions if you can think of a better way.

My recommendation would be to create a separate NPM registry that only stores VS Code extensions so you don't need scoped names.

**Comment by joelspadin-garmin** [comment]
Closing this as won't fix since it's a limitation of vscode/vsce, but do let me know if you have any ideas for workarounds.

**Comment by Greensleeves0906** [comment]
> I have verified that if the name has scope, it will report an error during `vsce package` and installation.
> 
> But in my company, if you want to publish the package , the name must with the scope

Have you solved this issue ? I have the same problem. @eightHundreds

**Comment by strazto** [comment]
A likely workaround is:

Remove the scope from the package name right before you package it with `vsce`, then change it pack to the scoped version to publish it to the registry

in package.json, change

```json
{
   "name" : "@my-org/my-package",
   "scripts" : {
		"prepublishOnly": "vsce package -o extension.vsix"
   }
}
```

to:

```bash
#!/usr/bin/env bash
# /scripts/prepublishOnly.sh

# make a copy of the manifest to swap back in
cp package.json package.json.real

# give vsce a manifest it views as "valid"
# replace:  "name" : "@my-org/my-package",
# with    :  "name" : "my-package",

sed --regexp-extended '/"name"\s*:/ s#@[a-zA-Z\\-]+/##' package.json.real > package.json

# or maybe prefix with npx
vsce package -o my-package.vsix

# now that it's built, restore the manifest to the one we'll use to publish
mv package.json.real package.json
```

```json
{
   "name" : "@my-org/my-package",
   "scripts" : {
		"prepublishOnly": "./scripts/prepublishOnly.sh"
   }
}
```

The sed command will change the "name" field temporarily to one `vsce` is happy with

```diff
--- package-old.json    2022-11-23 14:23:03.429829654 +1100
+++ package-new.json    2022-11-23 14:23:52.617742693 +1100
@@ -1,5 +1,5 @@
 {
-    "name" : "@my-org/my-package",
+    "name" : "my-package",
     "scripts" : {
          "prepublishOnly": "./scripts/prepublishOnly.sh"
     }
```

Better to use a node script, for `/scripts/prepublishOnly.sh` and `sed` tends to behave differently between gnu & macos distributions (so might not work), but this was the first thing i thought of
