### ISSUE TITLE
Question: is this extension able to notify users when a new version is released ?

### ISSUE THREAD

**Issue by damien-urruty-sonarsource** [joelspadin-garmin/vscode-private-extension-manager#25]
Hello !

Not really an issue here, more a question, because I was not able to find the information on the README, and I would like to know this before I give a try.

When users install this extension plus a private extension through it, will they be notified when an update of the private extension is released ? It's an interesting feature, that is available with the regular marketplace, so it might be worth mentioning the behavior in the README.

Anyway, thanks for this extension that seems useful!

**Comment by joelspadin-garmin** [comment]
Yes. It will periodically check for updates and notify you if a newer version of any installed extension is available. (You can control the check interval or disable it with the `privateExtensions.updateCheckInterval` setting.)

I'll add something to the readme about that setting. Thanks for letting me know it wasn't documented!
