### ISSUE TITLE
Managing different variants of same extension

### ISSUE THREAD

**Issue by offa** [joelspadin-garmin/vscode-private-extension-manager#36]
Is there a way to manage different versions of an extension? 

For example: [vscode-cpptools](https://github.com/microsoft/vscode-cpptools) has different VSIX files for each operating system, but all of them have the same package name and version.

Using different package names as a workaround enables pushing different variants into the registry, but it wont indicate installed plugins any more.

**Comment by joelspadin-garmin** [comment]
The published extensions are just NPM packages containing a .vsix file. There isn't currently a way to do this, though it would be possible to add multiple .vsix files to one package and then add extra fields to package.json that tells Private Extension Manager which one to use, for example based on the OS.

https://github.com/joelspadin-garmin/vscode-private-extension-manager/blob/1f4471728c80fa7922fc06aad829d8a935dbab36/extension/src/Package.ts#L287 would need to be updated to read these new fields to determine which .vsix file to use.

**Comment by offa** [comment]
Thanks for the hint, I'll give it a try.

**Comment by offa** [comment]
Implemented by #37
