### ISSUE TITLE
package.json publisher issue

### ISSUE THREAD

**Issue by SimoneRichetti** [joelspadin-garmin/vscode-private-extension-manager#40]
Hi,

I set up a Verdaccio private npm registry. I want to publish an extension to that private registry and then use the Private Extension Manager to install the extension from it. 
But, the `vscode package` command gives me an error, because the publisher field in my `package.json` does not contain a valid VSCode Marketplace Publisher token. And I can't simply remove the field from the JSON, because it is required.
Because I intend to publish only on the private registry, how can I solve the issue and create my `extension.vsix` file without registering a user on the Public VSCode Marketplace?

Thanks,
Simone

**Comment by joelspadin-garmin** [comment]
I assume you meant `vsce package`? As far as I can tell, you need to use a publisher name that would be valid if you were to publish to the public marketplace, but there is no requirement that said publisher exists. The name can only have letters, numbers, and hyphens: https://github.com/microsoft/vscode-vsce/blob/9f33d50e5b364cf49803e8324003547397505fed/src/validation.ts#L6

If that doesn't help, let me know and I can dig deeper into what vsce is doing.

**Comment by SimoneRichetti** [comment]
Ok, that was the error: I was using a publisher name with a dot in it. Now it works! Thanks!
