### ISSUE TITLE
Registry URL not respected

### ISSUE THREAD

**Issue by jorenbroekema** [joelspadin-garmin/vscode-private-extension-manager#43]
It seems like the extension is not respecting the URL that I put in.

For example:
```
"registry": "https://pkgs.dev.azure.com/foo/bar/_packaging/qux/npm/registry"
```

Produces a request to

```
https://pkgs.dev.azure.com/foo/bar/_packaging/qux/npm/registry/-/v1/search?text=*&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5
```

instead of

```
https://pkgs.dev.azure.com/foo/bar/_packaging/qux/npm/registry/search?text=*&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5
```

Why is `-/v1/` added?? That produces a 404 error, as expected, it should just use my registry URL as I provide it right?

**Comment by jorenbroekema** [comment]
I guess I should also add here that if you check the last link it will just find the npm package called `search`, it doesn't actually do a search. I guess I don't really understand what the extension manager is supposed to be doing with the registry URL, isn't it really dependent on the registry how you are supposed to search through extensions? And what exactly does it search for anyway? For packages that provide files that end with .vsix? And isn't that also highly dependent on the registry type, some have a "dist" array of files, some call it "files", how can the extension manager know how to search a registry and find the VSIX files?

**Comment by joelspadin-garmin** [comment]
It sounds like you're trying to implement your own server? The URL you provide should be the base URL for an NPM package registry. 

According to https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search, the REST endpoint for searching the registry is `/-/v1/search`. The extension will use this to discover the packages in the registry. Then it will query the other REST endpoints to get more information about the packages and the packages themselves (which, if you follow the [publishing documentation](https://github.com/joelspadin-garmin/vscode-private-extension-manager/tree/master/extension#publishing-extensions), will contain the .vsix file).

**Comment by jorenbroekema** [comment]
Hmm I'll take a further look to see if Azure Feeds actually are aligned with this registry API for npm packages, the thing with Azure feeds is it supports more things to be published on there than just NPM packages, so it's likely that a feed itself is not NPM Registry API compatible, but perhaps I need to append `/npm` to the feed URL or something.

**Comment by ameymodak1991** [comment]
I am trying to use JFrog's Artifactory and facing a similar issue. The search API supported by Artifactory is different than the npm registry.

Artifactory uses GET /api/search/artifact?name=
Ref: https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-SEARCHES

Is there any way to customize the search API? I am sure there will be other implementations that do not adhere to the npm registry implementation.

**Comment by jorenbroekema** [comment]
So yeah both Azure NPM Feeds and JFrog Artifactory don't seem to align with the official NPM registry API. That is not a problem of the extension of course. But I do have two suggestions before closing:

- Feature request to customize the search API to align with those services that don't use official NPM registry API. I'm not totally sure how much customization would be needed to make it work, whether it is just the search part or more..
- Add documentation stating that JFrog Artifactory / Azure NPM Feeds won't work and why

I added a suggestion for Microsoft to align API https://developercommunity.visualstudio.com/t/azure-feed-npm-registry-not-aligned-with-official/1388626 as well

**Comment by joelspadin-garmin** [comment]
Private Extension Manager currently uses NPM-specific modules such as https://github.com/npm/libnpmsearch for API calls. It would be possible to extract all the API call code and create an interface so you can swap between NPM and other APIs, but I didn't originally write the code with that in mind so I don't expect that to be easy.
