### ISSUE TITLE
vsce package always asks for a token

### ISSUE THREAD

**Issue by Netzeband** [joelspadin-garmin/vscode-private-extension-manager#89]
Hello

I'm just a VSCode user and not an extension developer.
However, I found a bug in one of the extensions I use and saw inside the code, that it is a one line change, which needs to be done here.
So my idea was to just clone the repository, do the change, create an VSIX file locally and install it in my VSCode installation. Of course I also tell the author of the extension about the bug, but before I get this fix, it will take some time.

However, every time when I do `vsce package` it asks me for an personal access token to Azure. I really don't want to publish anything, I don't have an Azure account, I don't need an Azure account, therefore I don't have a token. I don't want to have an account or token.

I cannot find any option to tell vsce to just create the VSIX file for me. I just found similar topics here in the repro like:
https://github.com/microsoft/vscode-vsce/pull/487 and https://github.com/microsoft/vscode-vsce/issues/328 but they don't have a real solution to that.

So how can I just create the VSIX files to manually install the extension to my local VSCode installation?

**Comment by joelspadin-garmin** [comment]
Are you using the Private Extension Manager extension? From your description, it sounds like you are just trying to package an extension and install it yourself, which means you don't need this extension.

https://github.com/microsoft/vscode-vsce would be the place to ask about issues with the vsce tool. 

For installing a VSIX locally, you don't need this extension. You can just run **F1 > Extensions: Install from VSIX**.

**Comment by Netzeband** [comment]
Oh yes, you are absolutely right. I have search so many github issues online, that I finally created my issue in the wrong github. Sorry for bothering you, I will ask my question at the vscode-vsce repository.
